# $schema: ../../schema.json
name: $meta
link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/meta/
minVersion: '4.4'
type:
  - resolvesToAny
encode: single
description: |
  Access available per-document metadata related to the aggregation operation.
arguments:
  - name: keyword
    type:
      - string
tests:
  - name: textScore
    link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/meta/#-meta---textscore-
    pipeline:
      - $match:
          $text:
            $search: cake
      - $group:
          _id:
            $meta: textScore
          count:
            $sum: 1
    schema:
      articles:
        _id:
          types:
            - bsonType: Number
        title:
          types:
            - bsonType: String
  - name: indexKey
    link: https://www.mongodb.com/docs/manual/reference/operator/aggregation/meta/#-meta---indexkey-
    pipeline:
      - $match:
          type: apparel
      - $addFields:
          idxKey:
            $meta: indexKey
    schema:
      orders:
        item:
          types:
            - bsonType: String
        price:
          types:
            - bsonType: Decimal128
        quantity:
          types:
            - bsonType: Number
        type:
          types:
            - bsonType: String
