# $schema: ../../schemas/operator.json
name: pipeline
link: https://www.mongodb.com/docs/manual/core/aggregation-pipeline/
minVersion: '1.0'
type:
  - pipeline
encode: single
wrapObject: false
description: |
  An aggregation pipeline consists of one or more stages that process documents. These documents can come from a collection, a view, or a specially designed stage.
arguments:
  - name: stages
    type:
      - stage
      - inputStage
      - outputStage
    variadic: array
    description: |-
      A list of stages
